services:
  # 1. MongoDB Service
  mongo:
    image: mongo:latest
    container_name: url-shortener-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - url-net

  # 2. Backend API Service
  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: url-shortener-api
    restart: on-failure  # Agar crash ho toh apne aap restart ho jaye
    ports:
      - "5000:5000"
    environment:
      # Logical Note: Yahan 'mongo' wahi naam hai jo upar service ka hai
      - MONGO_URI=mongodb://mongo:27017/shortener
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - url-net

# Data ko permanent rakhne ke liye (Named Volume)
volumes:
  mongo-data:

# Dono containers ke beech baat karne ke liye bridge network
networks:
  url-net:
    driver: bridge